//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PLCSTPARSER.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PLCSTPARSERParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPLCSTPARSERVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.startpoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartpoint([NotNull] PLCSTPARSERParser.StartpointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] PLCSTPARSERParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] PLCSTPARSERParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] PLCSTPARSERParser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.int_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_literal([NotNull] PLCSTPARSERParser.Int_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.signed_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_int([NotNull] PLCSTPARSERParser.Signed_intContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.binary_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_int([NotNull] PLCSTPARSERParser.Binary_intContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.octal_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOctal_int([NotNull] PLCSTPARSERParser.Octal_intContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.hex_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHex_int([NotNull] PLCSTPARSERParser.Hex_intContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.real_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReal_literal([NotNull] PLCSTPARSERParser.Real_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.bit_str_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBit_str_literal([NotNull] PLCSTPARSERParser.Bit_str_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.bool_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_literal([NotNull] PLCSTPARSERParser.Bool_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.char_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChar_literal([NotNull] PLCSTPARSERParser.Char_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.char_str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChar_str([NotNull] PLCSTPARSERParser.Char_strContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.d_byte_char_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitD_byte_char_value([NotNull] PLCSTPARSERParser.D_byte_char_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.time_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime_literal([NotNull] PLCSTPARSERParser.Time_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDuration([NotNull] PLCSTPARSERParser.DurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fix_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_point([NotNull] PLCSTPARSERParser.Fix_pointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval([NotNull] PLCSTPARSERParser.IntervalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.days"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDays([NotNull] PLCSTPARSERParser.DaysContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.hours"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHours([NotNull] PLCSTPARSERParser.HoursContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.minutes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinutes([NotNull] PLCSTPARSERParser.MinutesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.seconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeconds([NotNull] PLCSTPARSERParser.SecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.milliseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMilliseconds([NotNull] PLCSTPARSERParser.MillisecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.microseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMicroseconds([NotNull] PLCSTPARSERParser.MicrosecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.nanoseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNanoseconds([NotNull] PLCSTPARSERParser.NanosecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.time_of_day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime_of_day([NotNull] PLCSTPARSERParser.Time_of_dayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.daytime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDaytime([NotNull] PLCSTPARSERParser.DaytimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.day_hour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay_hour([NotNull] PLCSTPARSERParser.Day_hourContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.day_minute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay_minute([NotNull] PLCSTPARSERParser.Day_minuteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.day_second"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay_second([NotNull] PLCSTPARSERParser.Day_secondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] PLCSTPARSERParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.date_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_literal([NotNull] PLCSTPARSERParser.Date_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYear([NotNull] PLCSTPARSERParser.YearContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonth([NotNull] PLCSTPARSERParser.MonthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay([NotNull] PLCSTPARSERParser.DayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.date_and_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_and_time([NotNull] PLCSTPARSERParser.Date_and_timeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.data_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type_access([NotNull] PLCSTPARSERParser.Data_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.elem_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElem_type_name([NotNull] PLCSTPARSERParser.Elem_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.numeric_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_type_name([NotNull] PLCSTPARSERParser.Numeric_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.int_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_type_name([NotNull] PLCSTPARSERParser.Int_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.string_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_type_name([NotNull] PLCSTPARSERParser.String_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.bit_str_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBit_str_type_name([NotNull] PLCSTPARSERParser.Bit_str_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_type_access([NotNull] PLCSTPARSERParser.Derived_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.string_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_type_access([NotNull] PLCSTPARSERParser.String_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.single_elem_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_elem_type_access([NotNull] PLCSTPARSERParser.Single_elem_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.simple_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type_access([NotNull] PLCSTPARSERParser.Simple_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange_type_access([NotNull] PLCSTPARSERParser.Subrange_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_type_access([NotNull] PLCSTPARSERParser.Enum_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_access([NotNull] PLCSTPARSERParser.Array_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_type_access([NotNull] PLCSTPARSERParser.Struct_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.simple_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type_name([NotNull] PLCSTPARSERParser.Simple_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange_type_name([NotNull] PLCSTPARSERParser.Subrange_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_type_name([NotNull] PLCSTPARSERParser.Enum_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_name([NotNull] PLCSTPARSERParser.Array_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_type_name([NotNull] PLCSTPARSERParser.Struct_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.data_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type_decl([NotNull] PLCSTPARSERParser.Data_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_decl([NotNull] PLCSTPARSERParser.Type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_type_decl([NotNull] PLCSTPARSERParser.Derived_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_type_name([NotNull] PLCSTPARSERParser.Derived_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_spec_init([NotNull] PLCSTPARSERParser.Derived_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.simple_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_type_decl([NotNull] PLCSTPARSERParser.Simple_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.simple_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_spec_init([NotNull] PLCSTPARSERParser.Simple_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.simple_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_spec([NotNull] PLCSTPARSERParser.Simple_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange_type_decl([NotNull] PLCSTPARSERParser.Subrange_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange_spec_init([NotNull] PLCSTPARSERParser.Subrange_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange_spec([NotNull] PLCSTPARSERParser.Subrange_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange([NotNull] PLCSTPARSERParser.SubrangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_type_decl([NotNull] PLCSTPARSERParser.Enum_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.named_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_spec_init([NotNull] PLCSTPARSERParser.Named_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_spec_init([NotNull] PLCSTPARSERParser.Enum_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_value_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_value_spec([NotNull] PLCSTPARSERParser.Enum_value_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.enum_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_value([NotNull] PLCSTPARSERParser.Enum_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_decl([NotNull] PLCSTPARSERParser.Array_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_spec_init([NotNull] PLCSTPARSERParser.Array_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_spec([NotNull] PLCSTPARSERParser.Array_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_init([NotNull] PLCSTPARSERParser.Array_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_elem_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_elem_init([NotNull] PLCSTPARSERParser.Array_elem_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_elem_item_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_elem_item_init([NotNull] PLCSTPARSERParser.Array_elem_item_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_elem_init_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_elem_init_value([NotNull] PLCSTPARSERParser.Array_elem_init_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_type_decl([NotNull] PLCSTPARSERParser.Struct_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_spec([NotNull] PLCSTPARSERParser.Struct_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_spec_init([NotNull] PLCSTPARSERParser.Struct_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_decl([NotNull] PLCSTPARSERParser.Struct_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_elem_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_elem_decl([NotNull] PLCSTPARSERParser.Struct_elem_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_elem_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_elem_name([NotNull] PLCSTPARSERParser.Struct_elem_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_init([NotNull] PLCSTPARSERParser.Struct_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_elem_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_elem_init([NotNull] PLCSTPARSERParser.Struct_elem_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.str_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_type_decl([NotNull] PLCSTPARSERParser.Str_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_type_decl([NotNull] PLCSTPARSERParser.Ref_type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_spec_init([NotNull] PLCSTPARSERParser.Ref_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_spec([NotNull] PLCSTPARSERParser.Ref_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_type_name([NotNull] PLCSTPARSERParser.Ref_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_type_access([NotNull] PLCSTPARSERParser.Ref_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_name([NotNull] PLCSTPARSERParser.Ref_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_value([NotNull] PLCSTPARSERParser.Ref_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_addr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_addr([NotNull] PLCSTPARSERParser.Ref_addrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_assign([NotNull] PLCSTPARSERParser.Ref_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_deref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_deref([NotNull] PLCSTPARSERParser.Ref_derefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] PLCSTPARSERParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.symbolic_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolic_variable([NotNull] PLCSTPARSERParser.Symbolic_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.var_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_access([NotNull] PLCSTPARSERParser.Var_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.variable_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_name([NotNull] PLCSTPARSERParser.Variable_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.multi_elem_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulti_elem_var([NotNull] PLCSTPARSERParser.Multi_elem_varContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subscript_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript_list([NotNull] PLCSTPARSERParser.Subscript_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] PLCSTPARSERParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_variable([NotNull] PLCSTPARSERParser.Struct_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_elem_select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_elem_select([NotNull] PLCSTPARSERParser.Struct_elem_selectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.input_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_decls([NotNull] PLCSTPARSERParser.Input_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.input_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_decl([NotNull] PLCSTPARSERParser.Input_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.edge_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdge_decl([NotNull] PLCSTPARSERParser.Edge_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.var_decl_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl_init([NotNull] PLCSTPARSERParser.Var_decl_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ref_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_var_decl([NotNull] PLCSTPARSERParser.Ref_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_var_decl([NotNull] PLCSTPARSERParser.Interface_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.variable_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_list([NotNull] PLCSTPARSERParser.Variable_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_var_decl_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_var_decl_init([NotNull] PLCSTPARSERParser.Array_var_decl_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_conformand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_conformand([NotNull] PLCSTPARSERParser.Array_conformandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_conform_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_conform_decl([NotNull] PLCSTPARSERParser.Array_conform_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_var_decl_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_var_decl_init([NotNull] PLCSTPARSERParser.Struct_var_decl_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_decl_no_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_decl_no_init([NotNull] PLCSTPARSERParser.Fb_decl_no_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_decl_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_decl_init([NotNull] PLCSTPARSERParser.Fb_decl_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_name([NotNull] PLCSTPARSERParser.Fb_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_instance_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_instance_name([NotNull] PLCSTPARSERParser.Fb_instance_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.output_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_decls([NotNull] PLCSTPARSERParser.Output_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.output_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_decl([NotNull] PLCSTPARSERParser.Output_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.in_out_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_out_decls([NotNull] PLCSTPARSERParser.In_out_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.in_out_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_out_var_decl([NotNull] PLCSTPARSERParser.In_out_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] PLCSTPARSERParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.array_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_var_decl([NotNull] PLCSTPARSERParser.Array_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.struct_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_var_decl([NotNull] PLCSTPARSERParser.Struct_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decls([NotNull] PLCSTPARSERParser.Var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.retain_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetain_var_decls([NotNull] PLCSTPARSERParser.Retain_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.loc_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_var_decls([NotNull] PLCSTPARSERParser.Loc_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.loc_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_var_decl([NotNull] PLCSTPARSERParser.Loc_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.temp_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemp_var_decls([NotNull] PLCSTPARSERParser.Temp_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.external_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_var_decls([NotNull] PLCSTPARSERParser.External_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.external_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_decl([NotNull] PLCSTPARSERParser.External_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.global_var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var_name([NotNull] PLCSTPARSERParser.Global_var_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.global_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var_decls([NotNull] PLCSTPARSERParser.Global_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.global_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var_decl([NotNull] PLCSTPARSERParser.Global_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.global_var_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var_spec([NotNull] PLCSTPARSERParser.Global_var_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.loc_var_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_var_spec_init([NotNull] PLCSTPARSERParser.Loc_var_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.located_at"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocated_at([NotNull] PLCSTPARSERParser.Located_atContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.located_at_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocated_at_init([NotNull] PLCSTPARSERParser.Located_at_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.str_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_var_decl([NotNull] PLCSTPARSERParser.Str_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.s_byte_str_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitS_byte_str_var_decl([NotNull] PLCSTPARSERParser.S_byte_str_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.s_byte_str_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitS_byte_str_spec([NotNull] PLCSTPARSERParser.S_byte_str_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.d_byte_str_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitD_byte_str_var_decl([NotNull] PLCSTPARSERParser.D_byte_str_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.d_byte_str_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitD_byte_str_spec([NotNull] PLCSTPARSERParser.D_byte_str_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.loc_partly_var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_partly_var_decl([NotNull] PLCSTPARSERParser.Loc_partly_var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.loc_partly_var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_partly_var([NotNull] PLCSTPARSERParser.Loc_partly_varContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.var_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_spec([NotNull] PLCSTPARSERParser.Var_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_name([NotNull] PLCSTPARSERParser.Func_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_access([NotNull] PLCSTPARSERParser.Func_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_func_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_func_name([NotNull] PLCSTPARSERParser.Derived_func_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_decl([NotNull] PLCSTPARSERParser.Func_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.io_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIo_var_decls([NotNull] PLCSTPARSERParser.Io_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_var_decls([NotNull] PLCSTPARSERParser.Func_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body([NotNull] PLCSTPARSERParser.Func_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_type_name([NotNull] PLCSTPARSERParser.Fb_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_type_access([NotNull] PLCSTPARSERParser.Fb_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.derived_fb_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_fb_name([NotNull] PLCSTPARSERParser.Derived_fb_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_decl([NotNull] PLCSTPARSERParser.Fb_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_io_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_io_var_decls([NotNull] PLCSTPARSERParser.Fb_io_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_input_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_input_decls([NotNull] PLCSTPARSERParser.Fb_input_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_input_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_input_decl([NotNull] PLCSTPARSERParser.Fb_input_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_output_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_output_decls([NotNull] PLCSTPARSERParser.Fb_output_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_output_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_output_decl([NotNull] PLCSTPARSERParser.Fb_output_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.other_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOther_var_decls([NotNull] PLCSTPARSERParser.Other_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.no_retain_var_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_retain_var_decls([NotNull] PLCSTPARSERParser.No_retain_var_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_body([NotNull] PLCSTPARSERParser.Fb_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.method_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_decl([NotNull] PLCSTPARSERParser.Method_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.method_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_name([NotNull] PLCSTPARSERParser.Method_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.class_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_decl([NotNull] PLCSTPARSERParser.Class_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.class_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type_name([NotNull] PLCSTPARSERParser.Class_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.class_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_type_access([NotNull] PLCSTPARSERParser.Class_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_name([NotNull] PLCSTPARSERParser.Class_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.class_instance_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_instance_name([NotNull] PLCSTPARSERParser.Class_instance_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_decl([NotNull] PLCSTPARSERParser.Interface_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.method_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_prototype([NotNull] PLCSTPARSERParser.Method_prototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_spec_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_spec_init([NotNull] PLCSTPARSERParser.Interface_spec_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_value([NotNull] PLCSTPARSERParser.Interface_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_name_list([NotNull] PLCSTPARSERParser.Interface_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_type_name([NotNull] PLCSTPARSERParser.Interface_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_type_access([NotNull] PLCSTPARSERParser.Interface_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.interface_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_name([NotNull] PLCSTPARSERParser.Interface_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_decl([NotNull] PLCSTPARSERParser.Prog_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_type_name([NotNull] PLCSTPARSERParser.Prog_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_type_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_type_access([NotNull] PLCSTPARSERParser.Prog_type_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_access_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_access_decls([NotNull] PLCSTPARSERParser.Prog_access_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_access_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_access_decl([NotNull] PLCSTPARSERParser.Prog_access_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.sfc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSfc([NotNull] PLCSTPARSERParser.SfcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.sfc_network"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSfc_network([NotNull] PLCSTPARSERParser.Sfc_networkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.initial_step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitial_step([NotNull] PLCSTPARSERParser.Initial_stepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep([NotNull] PLCSTPARSERParser.StepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.step_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep_name([NotNull] PLCSTPARSERParser.Step_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.action_association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_association([NotNull] PLCSTPARSERParser.Action_associationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.action_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_name([NotNull] PLCSTPARSERParser.Action_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.action_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_qualifier([NotNull] PLCSTPARSERParser.Action_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.action_time"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction_time([NotNull] PLCSTPARSERParser.Action_timeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.indicator_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndicator_name([NotNull] PLCSTPARSERParser.Indicator_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.transition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransition([NotNull] PLCSTPARSERParser.TransitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.transition_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransition_name([NotNull] PLCSTPARSERParser.Transition_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.steps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSteps([NotNull] PLCSTPARSERParser.StepsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.transition_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransition_cond([NotNull] PLCSTPARSERParser.Transition_condContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] PLCSTPARSERParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.config_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig_name([NotNull] PLCSTPARSERParser.Config_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.resource_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_type_name([NotNull] PLCSTPARSERParser.Resource_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.config_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig_decl([NotNull] PLCSTPARSERParser.Config_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.resource_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_decl([NotNull] PLCSTPARSERParser.Resource_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.single_resource_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_resource_decl([NotNull] PLCSTPARSERParser.Single_resource_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.resource_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResource_name([NotNull] PLCSTPARSERParser.Resource_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.access_decls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_decls([NotNull] PLCSTPARSERParser.Access_declsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.access_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_decl([NotNull] PLCSTPARSERParser.Access_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.access_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_path([NotNull] PLCSTPARSERParser.Access_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.global_var_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobal_var_access([NotNull] PLCSTPARSERParser.Global_var_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.access_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_name([NotNull] PLCSTPARSERParser.Access_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_output_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_output_access([NotNull] PLCSTPARSERParser.Prog_output_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_name([NotNull] PLCSTPARSERParser.Prog_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.task_config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTask_config([NotNull] PLCSTPARSERParser.Task_configContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.task_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTask_name([NotNull] PLCSTPARSERParser.Task_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.task_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTask_init([NotNull] PLCSTPARSERParser.Task_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.data_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_source([NotNull] PLCSTPARSERParser.Data_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_config([NotNull] PLCSTPARSERParser.Prog_configContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_conf_elems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_conf_elems([NotNull] PLCSTPARSERParser.Prog_conf_elemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_conf_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_conf_elem([NotNull] PLCSTPARSERParser.Prog_conf_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_task"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_task([NotNull] PLCSTPARSERParser.Fb_taskContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_cnxn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_cnxn([NotNull] PLCSTPARSERParser.Prog_cnxnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.prog_data_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg_data_source([NotNull] PLCSTPARSERParser.Prog_data_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.data_sink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_sink([NotNull] PLCSTPARSERParser.Data_sinkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.config_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig_init([NotNull] PLCSTPARSERParser.Config_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.config_inst_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfig_inst_init([NotNull] PLCSTPARSERParser.Config_inst_initContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.namespace_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_decl([NotNull] PLCSTPARSERParser.Namespace_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.namespace_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_elements([NotNull] PLCSTPARSERParser.Namespace_elementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.namespace_h_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_h_name([NotNull] PLCSTPARSERParser.Namespace_h_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.namespace_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace_name([NotNull] PLCSTPARSERParser.Namespace_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.using_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsing_directive([NotNull] PLCSTPARSERParser.Using_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.pou_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPou_decl([NotNull] PLCSTPARSERParser.Pou_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.instruction_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_list([NotNull] PLCSTPARSERParser.Instruction_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_instruction([NotNull] PLCSTPARSERParser.Il_instructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_simple_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_simple_inst([NotNull] PLCSTPARSERParser.Il_simple_instContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_label([NotNull] PLCSTPARSERParser.Il_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_simple_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_simple_operation([NotNull] PLCSTPARSERParser.Il_simple_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_expr([NotNull] PLCSTPARSERParser.Il_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_jump_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_jump_operation([NotNull] PLCSTPARSERParser.Il_jump_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_invocation([NotNull] PLCSTPARSERParser.Il_invocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_formal_func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_formal_func_call([NotNull] PLCSTPARSERParser.Il_formal_func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_operand([NotNull] PLCSTPARSERParser.Il_operandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_operand_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_operand_list([NotNull] PLCSTPARSERParser.Il_operand_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_simple_inst_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_simple_inst_list([NotNull] PLCSTPARSERParser.Il_simple_inst_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_simple_instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_simple_instruction([NotNull] PLCSTPARSERParser.Il_simple_instructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_param_list([NotNull] PLCSTPARSERParser.Il_param_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_param_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_param_inst([NotNull] PLCSTPARSERParser.Il_param_instContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_param_last_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_param_last_inst([NotNull] PLCSTPARSERParser.Il_param_last_instContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_param_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_param_assign([NotNull] PLCSTPARSERParser.Il_param_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_param_out_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_param_out_assign([NotNull] PLCSTPARSERParser.Il_param_out_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_simple_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_simple_operator([NotNull] PLCSTPARSERParser.Il_simple_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_assignment([NotNull] PLCSTPARSERParser.Il_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.il_assign_out_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIl_assign_out_operator([NotNull] PLCSTPARSERParser.Il_assign_out_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] PLCSTPARSERParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.constant_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expr([NotNull] PLCSTPARSERParser.Constant_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXor_expr([NotNull] PLCSTPARSERParser.Xor_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expr([NotNull] PLCSTPARSERParser.And_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.compare_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare_expr([NotNull] PLCSTPARSERParser.Compare_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.equ_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqu_expr([NotNull] PLCSTPARSERParser.Equ_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd_expr([NotNull] PLCSTPARSERParser.Add_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] PLCSTPARSERParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.power_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPower_expr([NotNull] PLCSTPARSERParser.Power_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expr([NotNull] PLCSTPARSERParser.Unary_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expr([NotNull] PLCSTPARSERParser.Primary_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.variable_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_access([NotNull] PLCSTPARSERParser.Variable_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.multibit_part_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultibit_part_access([NotNull] PLCSTPARSERParser.Multibit_part_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] PLCSTPARSERParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt_list([NotNull] PLCSTPARSERParser.Stmt_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] PLCSTPARSERParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] PLCSTPARSERParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.assignment_attempt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_attempt([NotNull] PLCSTPARSERParser.Assignment_attemptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvocation([NotNull] PLCSTPARSERParser.InvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.subprog_ctrl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprog_ctrl_stmt([NotNull] PLCSTPARSERParser.Subprog_ctrl_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.param_assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_assign([NotNull] PLCSTPARSERParser.Param_assignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.selection_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_stmt([NotNull] PLCSTPARSERParser.Selection_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] PLCSTPARSERParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.case_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_stmt([NotNull] PLCSTPARSERParser.Case_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.case_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_selection([NotNull] PLCSTPARSERParser.Case_selectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.case_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_list([NotNull] PLCSTPARSERParser.Case_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.case_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_list_elem([NotNull] PLCSTPARSERParser.Case_list_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.iteration_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_stmt([NotNull] PLCSTPARSERParser.Iteration_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_stmt([NotNull] PLCSTPARSERParser.For_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.control_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl_variable([NotNull] PLCSTPARSERParser.Control_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.for_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_list([NotNull] PLCSTPARSERParser.For_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] PLCSTPARSERParser.While_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.repeat_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_stmt([NotNull] PLCSTPARSERParser.Repeat_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.ladder_diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLadder_diagram([NotNull] PLCSTPARSERParser.Ladder_diagramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.fb_diagram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFb_diagram([NotNull] PLCSTPARSERParser.Fb_diagramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PLCSTPARSERParser.reservedKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedKeyword([NotNull] PLCSTPARSERParser.ReservedKeywordContext context);
}
